/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_PSOC.h"
#include "Pin_S_A_1_aliases.h"
#include "Pin_S_A_1.h"
#include "Pin_S_A_aliases.h"
#include "Pin_S_A.h"
#include "Pin_LED_aliases.h"
#include "Pin_LED.h"
#include "ADC_SA1.h"
#include "Pin_PH_aliases.h"
#include "Pin_PH.h"
#include "Pin_LED_R_aliases.h"
#include "Pin_LED_R.h"
#include "Pin_LED_V_aliases.h"
#include "Pin_LED_V.h"
#include "UART_ESP.h"
#include "Pin_Bomba_aliases.h"
#include "Pin_Bomba.h"
#include "isr_rx2.h"
#include "PWM.h"
#include "Clock_1.h"
#include "pHe_aliases.h"
#include "pHe.h"
#include "pHr_aliases.h"
#include "pHr.h"
#include "timer_clock.h"
#include "timerpH.h"
#include "resetTimerpH.h"
#include "int_pH.h"
#include "UART_PSOC_IntClock.h"
#include "ADC_SA1_SAR.h"
#include "ADC_SA1_IntClock.h"
#include "ADC_SA1_TempBuf_dma.h"
#include "ADC_SA1_FinalBuf_dma.h"
#include "ADC_SA1_IRQ.h"
#include "UART_ESP_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

